### PR TITLE
Add topic-prefix for kafka output

### PR DESCRIPTION
**Pull request by mwdomino**
This PR adds a `topic-prefix` to the Kafka Output. When present, this prefix will be used to generate a separate Kafka topic per source. The topic name will follow `prefix_<source>`, and if there is a colon separating a port number as part of the source the colon will also be replaced with an underscore like `prefix_<source>_<port>` due to naming restrictions in Kafka topics.

I'm currently using this branch for testing in local development environments and all works as expected.

Let me know if you have any changes you'd like to ensure this keeps with the conventions used throughout the rest of the application, and thanks for the awesome work on gnmic as always!

### CODE REVIEW

**Comment by karimra** [comment]
Thanks for adding this option to the Kafka output.
Do you mind adding the subscription name as well? Just like it's done on NATS output [here](https://github.com/openconfig/gnmic/blob/main/pkg/outputs/nats_outputs/nats/nats_output.go#L409)

**Comment by mwdomino** [comment]
Great suggestion, I'll make the updates!

**Comment by karimra** [comment]
I meant adding it to the Kafka output as well, you would end up with `$prefix_$subscriptionName_$targetName`

**Comment by mwdomino** [comment]
I've updated this to capture the new formatting I believe. Let me know if you see anything else that you'd like modified.

**Review by karimra — APPROVED** [review]
Thanks for the contribution and for making the changes!

**Pull request merged**
