### PR TITLE
bump go version to 1.21.1

### PR DESCRIPTION
**Pull request by karimra**

### CODE REVIEW

**Review by hellt — APPROVED** [review]

**Comment by vincentbernat** [comment]
Is there a reason to bump the version in `go.mod`? This prevent dependencies to use Go 1.20 (which is still supported and present in distributions).

**Comment by karimra** [comment]
No specific reason. Which package do you import from gnmic ?

**Comment by vincentbernat** [comment]
`github.com/openconfig/gnmic/pkg/api`

**Comment by karimra** [comment]
would it be enough if I just downgrade that package's go version ?

**Comment by vincentbernat** [comment]
There are more dependencies to update. I am not really familiar on how to work when there are several `go.mod`.

```patch
 01:40 ❱ git diff
diff --git a/go.mod b/go.mod
index 0ec35ad7e1ce..cb18e40133c4 100644
--- a/go.mod
+++ b/go.mod
@@ -1,6 +1,6 @@
 module github.com/openconfig/gnmic

-go 1.21.1
+go 1.20

 require (
        github.com/Shopify/sarama v1.38.1
diff --git a/pkg/api/go.mod b/pkg/api/go.mod
index a73998b02a3c..fb02645a655f 100644
--- a/pkg/api/go.mod
+++ b/pkg/api/go.mod
@@ -1,6 +1,6 @@
 module github.com/openconfig/gnmic/pkg/api

-go 1.21.1
+go 1.20

 require (
        github.com/AlekSi/pointer v1.2.0
diff --git a/pkg/cache/go.mod b/pkg/cache/go.mod
index 5f6405153b9a..fc06c347cdac 100644
--- a/pkg/cache/go.mod
+++ b/pkg/cache/go.mod
@@ -1,6 +1,6 @@
 module github.com/openconfig/gnmic/pkg/cache

-go 1.21.1
+go 1.20

 require (
        github.com/go-redis/redis/v8 v8.11.5
diff --git a/pkg/path/go.mod b/pkg/path/go.mod
index 685e241df1aa..c849d802fea1 100644
--- a/pkg/path/go.mod
+++ b/pkg/path/go.mod
@@ -1,6 +1,6 @@
 module github.com/openconfig/gnmic/pkg/path

-go 1.21.1
+go 1.20

 require (
        github.com/google/go-cmp v0.6.0
diff --git a/pkg/target/go.mod b/pkg/target/go.mod
index bbc07e74e731..57407eb7a1f9 100644
--- a/pkg/target/go.mod
+++ b/pkg/target/go.mod
@@ -1,6 +1,6 @@
 module github.com/openconfig/gnmic/pkg/target

-go 1.21.1
+go 1.20

 require (
        github.com/jhump/protoreflect v1.15.3
diff --git a/pkg/testutils/go.mod b/pkg/testutils/go.mod
index c13f3d4d358b..855eb0c1882f 100644
--- a/pkg/testutils/go.mod
+++ b/pkg/testutils/go.mod
@@ -1,6 +1,6 @@
 module github.com/openconfig/gnmic/pkg/testutils

-go 1.21.1
+go 1.20

 require (
        github.com/google/go-cmp v0.6.0
diff --git a/pkg/types/go.mod b/pkg/types/go.mod
index 978c2494623c..45c0e9264c21 100644
--- a/pkg/types/go.mod
+++ b/pkg/types/go.mod
@@ -1,6 +1,6 @@
 module github.com/openconfig/gnmic/pkg/types

-go 1.21.1
+go 1.20

 require (
        github.com/openconfig/gnmic/pkg/utils v0.1.0
diff --git a/pkg/utils/go.mod b/pkg/utils/go.mod
index 9ed7926f1ec3..eb7d8c931555 100644
--- a/pkg/utils/go.mod
+++ b/pkg/utils/go.mod
@@ -1,5 +1,5 @@
 module github.com/openconfig/gnmic/pkg/utils

-go 1.21.1
+go 1.20

 require github.com/google/go-cmp v0.6.0
```

I think this patch should work, but running `go mod tidy -go=1.20` fails, because I suppose it uses the go version in the released versions, not the ones in the directory next to the current one.

```
 01:42 ❱ go mod tidy -go=1.20
go: github.com/openconfig/gnmic/pkg/path@v0.1.1 requires go@1.21.1, but 1.20 is requested
```

**Comment by karimra** [comment]
yes those are `pkg/api` dependencies, they would be downgraded as well. I'm trying to figure out what you have as direct imports.

**Comment by karimra** [comment]
>> I think this patch should work, but running go mod tidy -go=1.20 fails, because I suppose it uses the go version in the released versions, not the ones in the directory next to the current one.

correct, you will need a go.work file to point at the local pkg instead of the released ones.

**Comment by vincentbernat** [comment]
If this is complicated to downgrade dependencies, don't bother. 1.22 is released soon, and therefore 1.20 will become unsupported. In the future, if you can avoid an automatic bump of the version in go.mod, it will be helpful.

**Pull request merged**
