### PR TITLE
Cancel propagation

### PR DESCRIPTION
**Pull request by fahadnaeemkhan**
Following three issues are addressed:
1-   
   `errChan` in `gnmi_server.go.Subscribe()` is only used for the case `SubscriptionList_ONCE` so moved it under `SubscriptionList_ONCE` case

2- 
    notification listener on a.c.Subscribe(sc.stream.Context(), ro) can't return on err
    as this could block other senders on the same channel. Sender (subscription goroutine) closes the channel
    just before returning (using `defer`) and that would do.

3-
    in case of stream cancelation, error are popagated to gnmi_server.go.Subscribe()
    for proper clean up.

### CODE REVIEW

**Comment by karimra** [comment]
> 2- notification listener on a.c.Subscribe(sc.stream.Context(), ro) can't return on err as this could block other senders on the same channel. Sender (subscription goroutine) closes the channel just before returning (using `defer`) and that would do.

Which other senders are your considering here ?

**Comment by fahadnaeemkhan** [comment]
> > 2- notification listener on a.c.Subscribe(sc.stream.Context(), ro) can't return on err as this could block other senders on the same channel. Sender (subscription goroutine) closes the channel just before returning (using `defer`) and that would do.
> 
> Which other senders are your considering here ?

in Cache we create goroutine per subscription and if we have more than one subscription then we are doing to have more that one cache side goroutine (senders) and anyone of them can stop the listener by sending error.

I think better way stop listener is to close the channel when needed and is happening once `oc_cache.subscribe` return

```go
func (gc *gnmiCache) subscribe(ctx context.Context, ro *ReadOpts, ch chan *Notification) {
	defer close(ch)
	switch ro.Mode {
	case ReadMode_Once:
		gc.handleSingleQuery(ctx, ro, ch)
	case ReadMode_StreamOnChange: // default:
		ro.SuppressRedundant = false
		gc.handleOnChangeQuery(ctx, ro, ch)
	case ReadMode_StreamSample:
		gc.handleSampledQuery(ctx, ro, ch)
	}
}
```

**Comment by karimra** [comment]
> > > 2- notification listener on a.c.Subscribe(sc.stream.Context(), ro) can't return on err as this could block other senders on the same channel. Sender (subscription goroutine) closes the channel just before returning (using `defer`) and that would do.
> > 
> > 
> > Which other senders are your considering here ?
> 
> in Cache we create goroutine per subscription and if we have more than one subscription then we are doing to have more that one cache side goroutine (senders) and anyone of them can stop the listener by sending error.
> 
> I think better way to stop listener is to close the channel when needed and this is happening once `oc_cache.subscribe` returns
> 
> ```go
> func (gc *gnmiCache) subscribe(ctx context.Context, ro *ReadOpts, ch chan *Notification) {
> 	defer close(ch)
> 	switch ro.Mode {
> 	case ReadMode_Once:
> 		gc.handleSingleQuery(ctx, ro, ch)
> 	case ReadMode_StreamOnChange: // default:
> 		ro.SuppressRedundant = false
> 		gc.handleOnChangeQuery(ctx, ro, ch)
> 	case ReadMode_StreamSample:
> 		gc.handleSampledQuery(ctx, ro, ch)
> 	}
> }
> ```

Right but each subscription sends to a different channel. There is only one sender per channel, if it returns an error the channel will be closed right after.

**Comment by fahadnaeemkhan** [comment]
> > > > 2- notification listener on a.c.Subscribe(sc.stream.Context(), ro) can't return on err as this could block other senders on the same channel. Sender (subscription goroutine) closes the channel just before returning (using `defer`) and that would do.
> > > 
> > > 
> > > Which other senders are your considering here ?
> > 
> > 
> > in Cache we create goroutine per subscription and if we have more than one subscription then we are doing to have more that one cache side goroutine (senders) and anyone of them can stop the listener by sending error.
> > I think better way to stop listener is to close the channel when needed and this is happening once `oc_cache.subscribe` returns
> > ```go
> > func (gc *gnmiCache) subscribe(ctx context.Context, ro *ReadOpts, ch chan *Notification) {
> > 	defer close(ch)
> > 	switch ro.Mode {
> > 	case ReadMode_Once:
> > 		gc.handleSingleQuery(ctx, ro, ch)
> > 	case ReadMode_StreamOnChange: // default:
> > 		ro.SuppressRedundant = false
> > 		gc.handleOnChangeQuery(ctx, ro, ch)
> > 	case ReadMode_StreamSample:
> > 		gc.handleSampledQuery(ctx, ro, ch)
> > 	}
> > }
> > ```
> 
> Right but each subscription sends to a different channel. There is only one sender per channel, if it returns an error the channel will be closed right after.

I think each subscription sends to same channel:

```go
func (gc *gnmiCache) handleSingleQuery(ctx context.Context, ro *ReadOpts, ch chan *Notification) {
	if gc.debug {
		gc.logger.Printf("running single query for target %q", ro.Target)
	}

	caches := gc.getCaches(ro.Subscription)

	if gc.debug {
		gc.logger.Printf("single query got %d caches", len(caches))
	}
	wg := new(sync.WaitGroup)
	wg.Add(len(caches))

	for name, c := range caches {
		go func(name string, c *subCache) {
			defer wg.Done()
			for _, p := range ro.Paths {
				fp, err := path.CompletePath(p, nil)
				if err != nil {
					gc.logger.Printf("failed to generate CompletePath from %v", p)
					ch <- &Notification{Name: name, Err: err}
					return
				}
				err = c.c.Query(ro.Target, fp,
					func(_ []string, l *ctree.Leaf, _ interface{}) error {
						if err != nil {
							return err
						}
						switch gl := l.Value().(type) {
						case *gnmi.Notification:
							if ro.OverrideTS {
								// override timestamp
								gl = proto.Clone(gl).(*gnmi.Notification)
								gl.Timestamp = time.Now().UnixNano()
							}
							//no suppress redundant, send to channel and return
							if !ro.SuppressRedundant {
								ch <- &Notification{Name: name, Notification: gl}
								return nil
							}
							// suppress redundant part
							if ro.lastSent == nil {
								ro.lastSent = make(map[string]*gnmi.TypedValue)
								ro.m = new(sync.RWMutex)
							}

							prefix := utils.GnmiPathToXPath(gl.GetPrefix(), true)
							target := gl.GetPrefix().GetTarget()
							for _, upd := range gl.GetUpdate() {
								path := utils.GnmiPathToXPath(upd.GetPath(), true)
								valXPath := strings.Join([]string{target, prefix, path}, "/")
								ro.m.RLock()
								sv, ok := ro.lastSent[valXPath]
								ro.m.RUnlock()
								if !ok || !proto.Equal(sv, upd.Val) {
									ch <- &Notification{
										Name: name,
										Notification: &gnmi.Notification{
											Timestamp: gl.GetTimestamp(),
											Prefix:    gl.GetPrefix(),
											Update:    []*gnmi.Update{upd},
										},
									}
									ro.m.Lock()
									ro.lastSent[valXPath] = upd.Val
									ro.m.Unlock()
								}
							}

							if gl.GetDelete() != nil {
								ch <- &Notification{
									Name: name,
									Notification: &gnmi.Notification{
										Timestamp: gl.GetTimestamp(),
										Prefix:    gl.GetPrefix(),
										Delete:    gl.GetDelete(),
									},
								}
							}
							return nil
						}
						return nil
					})
				if err != nil {
					gc.logger.Printf("target %q failed internal cache query: %v", ro.Target, err)
					ch <- &Notification{Name: name, Err: err}
					return
				}
			}
		}(name, c)
	}
	wg.Wait()
}
```

**Comment by karimra** [comment]
The subscribe we are talking about is [here](https://github.com/openconfig/gnmic/blob/main/pkg/app/gnmi_server.go#L648).
In the case of the gnmiCache implementation it results in [this fn call](

> > > > > 2- notification listener on a.c.Subscribe(sc.stream.Context(), ro) can't return on err as this could block other senders on the same channel. Sender (subscription goroutine) closes the channel just before returning (using `defer`) and that would do.
> > > > 
> > > > 
> > > > Which other senders are your considering here ?
> > > 
> > > 
> > > in Cache we create goroutine per subscription and if we have more than one subscription then we are doing to have more that one cache side goroutine (senders) and anyone of them can stop the listener by sending error.
> > > I think better way to stop listener is to close the channel when needed and this is happening once `oc_cache.subscribe` returns
> > > ```go
> > > func (gc *gnmiCache) subscribe(ctx context.Context, ro *ReadOpts, ch chan *Notification) {
> > > 	defer close(ch)
> > > 	switch ro.Mode {
> > > 	case ReadMode_Once:
> > > 		gc.handleSingleQuery(ctx, ro, ch)
> > > 	case ReadMode_StreamOnChange: // default:
> > > 		ro.SuppressRedundant = false
> > > 		gc.handleOnChangeQuery(ctx, ro, ch)
> > > 	case ReadMode_StreamSample:
> > > 		gc.handleSampledQuery(ctx, ro, ch)
> > > 	}
> > > }
> > > ```
> > 
> > 
> > Right but each subscription sends to a different channel. There is only one sender per channel, if it returns an error the channel will be closed right after.
> 
> I think each subscription sends to same channel `ch`:
> 
> ```go
> func (gc *gnmiCache) handleSingleQuery(ctx context.Context, ro *ReadOpts, ch chan *Notification) {
> 	if gc.debug {
> 		gc.logger.Printf("running single query for target %q", ro.Target)
> 	}
> 
> 	caches := gc.getCaches(ro.Subscription)
> 
> 	if gc.debug {
> 		gc.logger.Printf("single query got %d caches", len(caches))
> 	}
> 	wg := new(sync.WaitGroup)
> 	wg.Add(len(caches))
> 
> 	for name, c := range caches {
> 		go func(name string, c *subCache) {
> 			defer wg.Done()
> 			for _, p := range ro.Paths {
> 				fp, err := path.CompletePath(p, nil)
> 				if err != nil {
> 					gc.logger.Printf("failed to generate CompletePath from %v", p)
> 					ch <- &Notification{Name: name, Err: err}
> 					return
> 				}
> 				err = c.c.Query(ro.Target, fp,
> 					func(_ []string, l *ctree.Leaf, _ interface{}) error {
> 						if err != nil {
> 							return err
> 						}
> 						switch gl := l.Value().(type) {
> 						case *gnmi.Notification:
> 							if ro.OverrideTS {
> 								// override timestamp
> 								gl = proto.Clone(gl).(*gnmi.Notification)
> 								gl.Timestamp = time.Now().UnixNano()
> 							}
> 							//no suppress redundant, send to channel and return
> 							if !ro.SuppressRedundant {
> 								ch <- &Notification{Name: name, Notification: gl}
> 								return nil
> 							}
> 							// suppress redundant part
> 							if ro.lastSent == nil {
> 								ro.lastSent = make(map[string]*gnmi.TypedValue)
> 								ro.m = new(sync.RWMutex)
> 							}
> 
> 							prefix := utils.GnmiPathToXPath(gl.GetPrefix(), true)
> 							target := gl.GetPrefix().GetTarget()
> 							for _, upd := range gl.GetUpdate() {
> 								path := utils.GnmiPathToXPath(upd.GetPath(), true)
> 								valXPath := strings.Join([]string{target, prefix, path}, "/")
> 								ro.m.RLock()
> 								sv, ok := ro.lastSent[valXPath]
> 								ro.m.RUnlock()
> 								if !ok || !proto.Equal(sv, upd.Val) {
> 									ch <- &Notification{
> 										Name: name,
> 										Notification: &gnmi.Notification{
> 											Timestamp: gl.GetTimestamp(),
> 											Prefix:    gl.GetPrefix(),
> 											Update:    []*gnmi.Update{upd},
> 										},
> 									}
> 									ro.m.Lock()
> 									ro.lastSent[valXPath] = upd.Val
> 									ro.m.Unlock()
> 								}
> 							}
> 
> 							if gl.GetDelete() != nil {
> 								ch <- &Notification{
> 									Name: name,
> 									Notification: &gnmi.Notification{
> 										Timestamp: gl.GetTimestamp(),
> 										Prefix:    gl.GetPrefix(),
> 										Delete:    gl.GetDelete(),
> 									},
> 								}
> 							}
> 							return nil
> 						}
> 						return nil
> 					})
> 				if err != nil {
> 					gc.logger.Printf("target %q failed internal cache query: %v", ro.Target, err)
> 					ch <- &Notification{Name: name, Err: err}
> 					return
> 				}
> 			}
> 		}(name, c)
> 	}
> 	wg.Wait()
> }
> ```

That is a single subscription that goes to multiple subcaches, in which case you are right multiple goroutines send to the same channel but that should not be solved there (return->continue). I think it should be solved within each cache implementation. 
In the case of the gnmiCache maybe adding a ctx with cancel, cancel it when a subCache query sends an error and select on ctx.Done() as well as sending to the channel would solve it ?

**Comment by fahadnaeemkhan** [comment]
> The subscribe we are talking about is [here](https://github.com/openconfig/gnmic/blob/main/pkg/app/gnmi_server.go#L648). In the case of the gnmiCache implementation it results in [this fn call](
> 
> > > > > > 2- notification listener on a.c.Subscribe(sc.stream.Context(), ro) can't return on err as this could block other senders on the same channel. Sender (subscription goroutine) closes the channel just before returning (using `defer`) and that would do.
> > > > > 
> > > > > 
> > > > > Which other senders are your considering here ?
> > > > 
> > > > 
> > > > in Cache we create goroutine per subscription and if we have more than one subscription then we are doing to have more that one cache side goroutine (senders) and anyone of them can stop the listener by sending error.
> > > > I think better way to stop listener is to close the channel when needed and this is happening once `oc_cache.subscribe` returns
> > > > ```go
> > > > func (gc *gnmiCache) subscribe(ctx context.Context, ro *ReadOpts, ch chan *Notification) {
> > > > 	defer close(ch)
> > > > 	switch ro.Mode {
> > > > 	case ReadMode_Once:
> > > > 		gc.handleSingleQuery(ctx, ro, ch)
> > > > 	case ReadMode_StreamOnChange: // default:
> > > > 		ro.SuppressRedundant = false
> > > > 		gc.handleOnChangeQuery(ctx, ro, ch)
> > > > 	case ReadMode_StreamSample:
> > > > 		gc.handleSampledQuery(ctx, ro, ch)
> > > > 	}
> > > > }
> > > > ```
> > > 
> > > 
> > > Right but each subscription sends to a different channel. There is only one sender per channel, if it returns an error the channel will be closed right after.
> > 
> > 
> > I think each subscription sends to same channel `ch`:
> > ```go
> > func (gc *gnmiCache) handleSingleQuery(ctx context.Context, ro *ReadOpts, ch chan *Notification) {
> > 	if gc.debug {
> > 		gc.logger.Printf("running single query for target %q", ro.Target)
> > 	}
> > 
> > 	caches := gc.getCaches(ro.Subscription)
> > 
> > 	if gc.debug {
> > 		gc.logger.Printf("single query got %d caches", len(caches))
> > 	}
> > 	wg := new(sync.WaitGroup)
> > 	wg.Add(len(caches))
> > 
> > 	for name, c := range caches {
> > 		go func(name string, c *subCache) {
> > 			defer wg.Done()
> > 			for _, p := range ro.Paths {
> > 				fp, err := path.CompletePath(p, nil)
> > 				if err != nil {
> > 					gc.logger.Printf("failed to generate CompletePath from %v", p)
> > 					ch <- &Notification{Name: name, Err: err}
> > 					return
> > 				}
> > 				err = c.c.Query(ro.Target, fp,
> > 					func(_ []string, l *ctree.Leaf, _ interface{}) error {
> > 						if err != nil {
> > 							return err
> > 						}
> > 						switch gl := l.Value().(type) {
> > 						case *gnmi.Notification:
> > 							if ro.OverrideTS {
> > 								// override timestamp
> > 								gl = proto.Clone(gl).(*gnmi.Notification)
> > 								gl.Timestamp = time.Now().UnixNano()
> > 							}
> > 							//no suppress redundant, send to channel and return
> > 							if !ro.SuppressRedundant {
> > 								ch <- &Notification{Name: name, Notification: gl}
> > 								return nil
> > 							}
> > 							// suppress redundant part
> > 							if ro.lastSent == nil {
> > 								ro.lastSent = make(map[string]*gnmi.TypedValue)
> > 								ro.m = new(sync.RWMutex)
> > 							}
> > 
> > 							prefix := utils.GnmiPathToXPath(gl.GetPrefix(), true)
> > 							target := gl.GetPrefix().GetTarget()
> > 							for _, upd := range gl.GetUpdate() {
> > 								path := utils.GnmiPathToXPath(upd.GetPath(), true)
> > 								valXPath := strings.Join([]string{target, prefix, path}, "/")
> > 								ro.m.RLock()
> > 								sv, ok := ro.lastSent[valXPath]
> > 								ro.m.RUnlock()
> > 								if !ok || !proto.Equal(sv, upd.Val) {
> > 									ch <- &Notification{
> > 										Name: name,
> > 										Notification: &gnmi.Notification{
> > 											Timestamp: gl.GetTimestamp(),
> > 											Prefix:    gl.GetPrefix(),
> > 											Update:    []*gnmi.Update{upd},
> > 										},
> > 									}
> > 									ro.m.Lock()
> > 									ro.lastSent[valXPath] = upd.Val
> > 									ro.m.Unlock()
> > 								}
> > 							}
> > 
> > 							if gl.GetDelete() != nil {
> > 								ch <- &Notification{
> > 									Name: name,
> > 									Notification: &gnmi.Notification{
> > 										Timestamp: gl.GetTimestamp(),
> > 										Prefix:    gl.GetPrefix(),
> > 										Delete:    gl.GetDelete(),
> > 									},
> > 								}
> > 							}
> > 							return nil
> > 						}
> > 						return nil
> > 					})
> > 				if err != nil {
> > 					gc.logger.Printf("target %q failed internal cache query: %v", ro.Target, err)
> > 					ch <- &Notification{Name: name, Err: err}
> > 					return
> > 				}
> > 			}
> > 		}(name, c)
> > 	}
> > 	wg.Wait()
> > }
> > ```
> 
> That is a single subscription that goes to multiple subcaches, in which case you are right multiple goroutines send to the same channel but that should not be solved there (return->continue). I think it should be solved within each cache implementation. In the case of the gnmiCache maybe adding a ctx with cancel, cancel it when a subCache query sends an error and select on ctx.Done() as well as sending to the channel would solve it ?

So cleanup if any of the cache-goroutine hit the error?

**Comment by fahadnaeemkhan** [comment]
On a separate note, what is the use if `sc.errChan` in `gnmi_server.Subscribe` as this is send_only and no one is reading from it.

**Comment by karimra** [comment]
> So cleanup if any of the cache-goroutine hit the error?

yes

**Comment by karimra** [comment]
> On a separate note, what is the use of `sc.errChan` in `gnmi_server.Subscribe` as this is send only so no one is reading from it.

It probably can replace the errChan in that function, I have to find some time to look into that part of the code again.

**Comment by fahadnaeemkhan** [comment]
PR got closed as i had to delete the branch.

New PR: https://github.com/openconfig/gnmic/pull/32

**Pull request closed without merging**
